### ISSUE TITLE
PSRule task ps-rule-assert@1 cannot analyze objects from JSON files in 'out/'. anymore

### ISSUE THREAD

**Issue by bengeset96** [microsoft/PSRule#1025] opened 2022-03-22 09:11 UTC
Hi, 

We are using PSRule in our environments to validate infrastructure as code and really been enjoying it!

Lately we have gotten a problem where PSRule cannot analyze the objects from JSON files, both on Microsoft hosted-agent and private hosted agent. It has worked without any hiccups until now. 

Using this:

`Export-AzRuleTemplateData -TemplateFile $TemplateFileJson -ParameterFile $parameterFilePath -OutputPath out/`

This is what is then put to out/'

![image (13)](https://user-images.githubusercontent.com/99641908/159444877-f24ffafa-ebc0-4baf-8b70-6d3684924fcc.png)

```
# Run analysis from JSON files using the `PSRule.Rules.Azure` module
      - task: ps-rule-assert@1
        continueOnError: false
        displayName: 'Analyze Azure template files'
        inputs:
          inputType: inputPath
          inputPath: 'out/*.json'                  # Read exported resource data from out/..
          modules: 'PSRule.Rules.Azure'            # Analyze objects using the rules within the PSRule.Rules.Azure PowerShell module.
          outputFormat: NUnit3                     # Save results to an NUnit report.
          outputPath: reports/ps-rule-results.xml  # Write NUnit report to 'reports/ps-rule-results.xml'.
```
Not working anymore:

![image (10)](https://user-images.githubusercontent.com/99641908/159444067-26c4b023-2ea5-4eb8-b8f8-3a290c2c34d9.png)

Doing it with pwsh in script instead, then it works:

![image (11)](https://user-images.githubusercontent.com/99641908/159444165-d650555d-0072-499f-ba80-5b3e6a6aae3e.png)

![image (12)](https://user-images.githubusercontent.com/99641908/159444363-ab379609-b4e8-483b-bbe2-d0258c8aa840.png)

Do the project maintainers or contributors have any clue what this might be or experienced something similar? Have there been any change in the ps-rule-assert@1 task lately? Have also tried with ps-rule-assert@0, same behaviour =(

**Comment by BernieWhite** [comment] 2022-03-22 10:32
@bengeset96 Thanks for reporting the issue. Are you able to provide the version of the task reported at the top of the `ps-rule-assert@1` log when executing?

**Comment by bengeset96** [comment] 2022-03-22 10:36
Sure thing @BernieWhite !

```
Starting: Analyze Azure template files
==============================================================================
Task         : PSRule analysis
Description  : Run analysis with PSRule.
Version      : 1.0.2201013
Author       : Bernie White
Help         : https://github.com/Microsoft/PSRule-pipelines/blob/main/docs/tasks.md#ps-rule-assert
```

**Comment by BernieWhite** [comment] 2022-03-22 10:46
@bengeset96 We don't have issues currently logged for your issue. Thanks for reporting it. We'll see if we can reproduce the issue.

Also can I ask a few more questions:

- Is the PowerShell `Export-AzRuleTemplateData` called in the same job as the `ps-rule-assert@1` task, or separate jobs.
- Do you have anything set in the `ps-rule.yaml` options file specifically under `input:`?
- Are you setting any additional environment variables with the `PSRULE_` prefix? If so, which ones.

Thanks.

**Comment by BernieWhite** [comment] 2022-03-22 10:48
You can enable verbose logging by running the pipeline with the `SYSTEM_DEBUG` variable set to `true`. This might help identify the issue.

**Comment by bengeset96** [comment] 2022-03-22 10:55
@BernieWhite 

Is the PowerShell Export-AzRuleTemplateData called in the same job as the ps-rule-assert@1 task, or separate jobs.

Same job, but seperate tasks, actually in a script that is coming before the the ps-rule-assert@1 task. 

Do you have anything set in the ps-rule.yaml options file specifically under input:?

Yes. 

```
#
# PSRule configuration
#
# Please see the documentation for all configuration options:
# https://microsoft.github.io/PSRule/
# https://azure.github.io/PSRule.Rules.Azure/setup/configuring-options/

input:
  pathIgnore:
  - '**/*'
  - 'refs/heads/main'
  - '!modules/**/.tests/*.json'

include:
  path: []
  module:
  # Allow local testing in Visual Studio Code
  # https://azure.github.io/PSRule.Rules.Azure/validating-locally/
  - 'PSRule.Rules.Azure'

output:
  culture:
  - en-US

configuration:
  # Enable automatic expansion of Azure parameter files
  AZURE_PARAMETER_FILE_EXPANSION: true

  # Bicep is experimental and currently disabled as testing occurs against compiled template
  # Enable automatic expansion of bicep source files
  #AZURE_BICEP_FILE_EXPANSION: true
```
Are you setting any additional environment variables with the PSRULE_ prefix? If so, which ones.

No, currently not using any additional environment variables. 

I will try to enable verbose logging!

**Comment by BernieWhite** [comment] 2022-03-22 11:00
@bengeset96 I suspect the `input.pathIgnore` setting is the culprit.

Try updating that section to:

```yaml
input:
  pathIgnore:
  - '**/*'
  - 'refs/heads/main'
  - '!modules/**/.tests/*.json'
  - '!out/*.json'
```

**Comment by bengeset96** [comment] 2022-03-22 12:12
@BernieWhite 

What you suspected was spot on! 

It is now working correctly. Can't believe it was something like that! The devil is in the details..

Thank you so much, words cannot describe how thankful I am for all the help and support you have given!

**Comment by BernieWhite** [comment] 2022-03-22 12:18
@bengeset96 No worries. Happy that PSRule is working great for you.

Explaining your issue a little more:

- `**/*` excludes all files including `out/`.
- Why does the task not work? Because of `inputPath: 'out/*.json'` in `out/`.
- Why does the `Assert-PSRule` command work, shouldn't it be the same? You are using `$templateData.FullName` which is the direct path to the specific file. If you pass PSRule the exact path to a file it will still accept the file even though a less specific path was excluded. If you pass the exact file name to the `ps-rule-assert@1` task it should behave the same way.

Hope that makes sense.

**Comment by BernieWhite** [comment] 2022-03-22 12:23
@bengeset96 I think we can close this issue since the problem was resolved. If you encounter any different issues please log a new issue. Thanks

**Closed by BernieWhite** 2022-03-22 12:23 UTC
